# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a292816b216e90edc49fd5cc06da2fab21a7dafe63b9160e2324367855ce5fa4b2390ac61a3443c48ad5d1317744224e61f4bfb9753776643b8828abe512efd

test:
  secret_key_base: d9d6373e9a5726f32cfaadc4879583899df46ba46fbec7922d1527dc22e5f4c5f91cb5a98e6dcced2873f878c040ccf7cd57fd12d21404f6b7448553adbc3cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
